### ISSUE TITLE
get_constituents returns error on historical dates

### ISSUE THREAD

**Issue by ceaza** [vfilimonov/pydatastream#1]
This seems to work in line 473  
      res = pd.DataFrame({fld:[record[fld_name(fld,ind)]if fld_name(fld,ind) in record else 'N/A'  for ind in range(num)]for fld in fields})

Tested for call DWE.get_constituents('JSEOVER', '28-Dec-2009')

**Comment by ceaza** [comment]
Hi Vladimir

Are you aware of a method of requesting the available datatypes/fields per
instrument code? I can see this on web navigator
<http://product.datastream.com/navigator/Search.aspx?AppGroup=DSAddin>but
am not able to do this through code.

Thanks
Charles

On Sat, Nov 8, 2014 at 2:10 PM, Vladimir Filimonov <notifications@github.com

**Comment by vfilimonov** [comment]
No, unfortunately I did not look into it.

I can only suggest you to contact the support (usually they're quite helpful):
https://customers.reuters.com/sc/Contactus/simple/?product=Datastream&env=PU&TP=Y

Cheers 
Vladimir

p.s. this (I think quite though rather outdated) document that I once have found:
https://www.dropbox.com/s/mkextt6dgwzgqh0/Datastream_dataypes.pdf?dl=0
could be of a help as well...

**Comment by ceaza** [comment]
Thanks very much for your help!

On Thu, Feb 5, 2015 at 4:25 PM, Vladimir Filimonov <notifications@github.com
