### ISSUE TITLE
Compatible with pandas

### ISSUE THREAD

**Issue by carlaxin2** [vfilimonov/pydatastream#12]
Last month, pandas upgraded from 0.19 to 0.20. And they release a warning : "Panel is deprecated and will be removed in a future version". However, your pydatastream package will output in pandas when the output is 3-dimension. Therefore, I am wondering whether you will follow up pandas.

Thank you so much.

**Comment by vfilimonov** [comment]
Good point! I've updated it and starting version 0.5.0 (https://github.com/vfilimonov/pydatastream/commit/fcb6dbb3ab535f0487de969734dd8a57a0197010) method `fetch()` will return MultiIndex instead of Panel 

I've never liked Panels anyway. ;-)
