### ISSUE TITLE
DSPermissionPassword

### ISSUE THREAD

**Issue by handrew** [vfilimonov/pydatastream#17]
I'm getting the following error (though things were working as recently as a few days ago). Do you know why this might be happening?

suds.WebFault: b"Server raised fault: 'User 'DS:XXXXXX' logon failed: Delegate Source 'DSPermissionsPassword' reports: No response from source DSPermissionsPassword'"

**Comment by handrew** [comment]
I just got off the phone with some of their support folk. They said that they are phasing out access to Datastream via DataWorks Enterprise, and that we should use Datastream Web Services (DSWS) now.

**Comment by vfilimonov** [comment]
Hello @handrew , thanks for letting me know!

A couple of questions:
- Did they tell if they're going to shut down the old API completely or only not supporting it any more? The discontinuation would be quite a burden to rewrite and retest all interfaces...
- Have you perhaps looked at DSWS, if it is very different from DWE? I wonder if the library could be easily fixed to use soap DSWS instead...

**Comment by handrew** [comment]
Hey,

- Regarding the old API: you might wanna check out [this link](https://community.developers.thomsonreuters.com/questions/30505/dspermissionpassword-not-working-in-soap-api.html). Looks like they fixed it, but it's still going to be "retired", whatever that means.

Also, they said to me in a support ticket: "Upon further checking, DWE is already being decommissioned and a new API is in place. The new API for Datastream needs additional entitlement."

- With respect to DSWS vs. DWE: I don't know, unfortunately. I'm trying to migrate over to to DSWS but I think that my Eikon w/ DFO subscription doesn't cover it. I'm working this out right now. Looks like it's going to be quite different.  However, it seems like someone else (who cited you, actually) has put together a [Python library for DSWS](https://github.com/hoenie-ams/PyDSWS). 

Hope this helps, let me know if anything relevant comes your way.

**Comment by handrew** [comment]
Further information relating to [Eikon w/ DFO access](https://community.developers.thomsonreuters.com/questions/30525/dsws-and-eikon-dfo.html?childToView=30555#answer-30555) to PyDSWS. Looks promising!

**Comment by vfilimonov** [comment]
Thank you for the information @handrew ! I will read into this.

The guy from the PyDSWS looks to be working at Thomson Reuters which is good! :-) I hope that at some point they will make official libraries for Python/R - it's hard to imagine that this would take a lot of efforts for a company like TR...
