### ISSUE TITLE
Unable to install this package

### ISSUE THREAD

**Issue by SanthoshAshokkumar** [vfilimonov/pydatastream#19]
Unable to install this package. Unable to install the dependency package suds-py3 too. I am currently using Python 3.6 (Using Pycharm as IDE and Miniconda for Python). Kindly help me with what am I missing in order to get this package ?

**Comment by vfilimonov** [comment]
Hello @SanthoshAshokkumar 
Sorry for the late response. Since the old DWE is discontinued (https://github.com/vfilimonov/pydatastream/issues/22) I'm rewriting the code for new API. New version will be released soon and will not depend on SUDS.
