### ISSUE TITLE
Access problem

### ISSUE THREAD

**Issue by Ingovs** [vfilimonov/pydatastream#21]
Hello, when trying to access my account, I receive the following error.

- DWE = Datastream(username="DS:XXXXXX", password="XXXXXXXX")

b"Server raised fault: 'User 'DS:XXXXXX' logon failed: Delegate Source 'DSPermissionsPassword' reports: No response from source DSPermissionsPassword'"

It was working just last week. I don't know if it's a problem with Datastream's server.

Do you know what it might be?

**Comment by MikeMccree** [comment]
Experiencing the same issue on my side, **unfortunately** I have no solution yet.

Having someone from Reuters look into this. Will update you with any feedback they provide.

Mike

**Comment by vfilimonov** [comment]
Hello @Ingovs @MikeMccree 

Thank you for the reporting this! Unfortunately I don't have access to DWE at the moment, so I could not check on my side.

But I would appreciate if you could post the response from TR here, in case someone else has the same issues.

Vladimir

**Comment by ajennings6767** [comment]
Has anyone had any traction w/ TR on this?

**Comment by MikeMccree** [comment]
Last I heard was TR had engaged their order management team and would have a solution by Monday (15th)
Will be reaching out again today & will update this post.

**Comment by ZanLondon** [comment]
Hi. Do you have any update on this ? It stopped working for me as well.
Thanks a lot.

**Comment by MikeJonessss** [comment]
Hi, what i understood is that Reuters closed the DWE api and now only has the DSWS api. I received the following mail:

Please note that Dataworks Enterprise (DWE) which is an old web service providing Datastream data has reached its end-of-life as of 1st July 2019.

Note that service is no longer available from following (Matlab, EViews, Python or R) URLs:
http://dataworks.thomson.com/dataworks/enterprise/1.0/webServiceClient.asmx
http://europe.dataworks.thomson.com/dataworks/enterprise/1.0/webServiceClient.asmx
http://us.dataworks.thomson.com/dataworks/enterprise/1.0/webServiceClient.asmx

More information is available at https://developers.refinitiv.com/eikon-apis/datastream-web-service

@vfilimonov i really loved some features in your code, like the PiT stuff. Would it be possible for you to integrate the DSWS api? Thanks you very much.

**Comment by vfilimonov** [comment]
Hello all

@MikeJonesss, thank you for confirmation, that DWE has been discontinued! I will add it to the front page.

Migration to the new API looks not difficult - as it is a simple REST. The main problem is that since a few years I don't have subscription to DWE anymore. So at the moment I could not continue development, migrate the library to the new interface and be responsible for bugs fixing. That's quite a pity since the library is often used apparently. If I regain access at some point, I would certainly do this (I might ask TR directly for that).

Meanwhile there is at least one library implementing DSWS: https://github.com/hoenie-ams/PyDSWS

Best
Vladimir

**Comment by vfilimonov** [comment]
OK, I'm on it - hopefully will release a new version within a week

**Comment by MikeJonessss** [comment]
awesome! i look forward testing it.

**Comment by vfilimonov** [comment]
Hello all

So, the updated version is on the master:
```
pip install git+https://github.com/vfilimonov/pydatastream.git
```

it works fine on my side, @MikeJonessss, @ZanLondon, @MikeMccree , @Ingovs please have a look. 
If there're no issues - next week I'll release it on pypi.
I'd appreciate if you could test it on as many use cases as possible.

**Comment by MikeJonessss** [comment]
Unfortunately I get an error installing it, but I think it is unrelated to your package:
ERROR: Command errored out with exit status 128

I copied your code in pydatastream.py and just saved in in my local module, not sure if that is ok. But i get an error that my credentials are not recognized:
 b"Server raised fault: 'User 'ZXXX000' logon failed: Unrecognised credentials'" 
With other packages I do not get this error.

There is a bug in line 159 of pydatastream.py: warngins needs to be warnings

**Comment by vfilimonov** [comment]
Hello @MikeJonessss, thanks for reporting!

> Unfortunately I get an error installing it, but I think it is unrelated to your package:
ERROR: Command errored out with exit status 128

This is strange, do you install from github as in the previous comment?
Do you use python 2 or python 3?

Also - could you please paste the full log of `pip install git+https://github.com/vfilimonov/pydatastream.git`?

> But i get an error that my credentials are not recognized:
b"Server raised fault: 'User 'ZXXX000' logon failed: Unrecognised credentials'"

This is also strange. Invalid credentials error should not copy username, like here:
```
---------------------------------------------------------------------------
DatastreamException                       Traceback (most recent call last)
<ipython-input-8-4eeb6f34d2ac> in <module>
      1 from pydatastream import Datastream
----> 2 DS = Datastream("....", "....")

~/Work/Library/pydatastream/pydatastream/pydatastream.py in __init__(self, username, password, raise_on_error, proxy, **kwargs)
    119         self._password = password
    120         # request new token
--> 121         self.renew_token(username, password)
    122 
    123     ###########################################################################

~/Work/Library/pydatastream/pydatastream/pydatastream.py in renew_token(self, username, password)
    160             return
    161         data = {"UserName": username, "Password": password}
--> 162         self._token = dict(self._api_post('GetToken', data))
    163         self._token['TokenExpiry'] = _parse_dates(self._token['TokenExpiry'])
    164 

~/Work/Library/pydatastream/pydatastream/pydatastream.py in _api_post(self, method, request)
    150             errormsg = f'{code}: {response["Message"]}'
    151             self.last_request['error'] = errormsg
--> 152             raise DatastreamException(errormsg)
    153         return self.last_request['response']
    154 

DatastreamException: InvalidCredentials: Invalid credentials were supplied. You are not logged in.
```
Could it be that there's some issue with paths and you're importing the pydatastream of version 0.5? 

> There is a bug in line 159 of pydatastream.py: warngins needs to be warnings

Right, thanks a lot! Fixed.

**Comment by MikeJonessss** [comment]
I managed to install it from the zipfile, I works fine now! So far I have not had any issues. Thank you very much for updating the package @vfilimonov !

**Comment by vfilimonov** [comment]
The new version is in the pypi since August 27 and usual `pip install pydatastream` works fine on my side. I'm closing this issue - in case if there're any problems - feel free to open a new ticket
