### ISSUE TITLE
0.6.2 missing on pypi

### ISSUE THREAD

**Issue by MikaelUmaN** [vfilimonov/pydatastream#24]
Hi.

Really appreciate this convenient library. Is it possible to get 0.6.2 on pypi?

I can just use this source code of course but would be nice to have it available from pip.

Regards,
Mikael

**Comment by vfilimonov** [comment]
Hi @MikaelUmaN , thank you for the feedback! Indeed, I should have pushed it a while ago.
It is now on pypi. Please have a look and let me know if there're any issues.

**Comment by MikaelUmaN** [comment]
Thanks for the quick response and action :)!

Also, Eric Lundgren says hello from across my desk.

Small world !
