### ISSUE TITLE
Deprecated pandas.np module

### ISSUE THREAD

**Issue by ewildiers** [vfilimonov/pydatastream#25]
Since upgrading to pandas 1.0.3 the following warning appears when calling DS.fetch:

"/site-packages/pydatastream/pydatastream.py:335: FutureWarning: The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead"

Should be an easy case of replacing pd.np.NaN by np.NaN where appropriate

@vfilimonov  Happy to do the PR for this if you like?

**Comment by vfilimonov** [comment]
Hello @ewildiers 
Thanks for the report and the suggestion! 
I have already pushed the change to master. Will need to upgrade my pandas and check that nothing else is broken (it should not) and then push it to pypi
