### ISSUE TITLE
Query an instrument using its SEDOL / RIC

### ISSUE THREAD

**Issue by micycle1** [vfilimonov/pydatastream#30]
Is it possible to fetch data of an instrument using its SEDOL or RIC field? ISIN and Mnemonic seem to work with `DS.fetch()`, but querying based on other fields (like SEDOL and RIC) do not -- is this a limitation of the library or the API?

**Comment by vfilimonov** [comment]
It should be possible, but I suspect that you would need a special query string for that. Once you have a string, you could simply use it in the fetch method.

Unfortunately I could not consult you on this, as I’ve never used it. Please ask the support of Reginitiv.

**Comment by micycle1** [comment]
For RICs, they can be enclosed with `<` and `>` and then searched as normal, e.g. `<AAPL.O>`.
