### ISSUE TITLE
Use behind a proxy

### ISSUE THREAD

**Issue by alastairbs** [vfilimonov/pydatastream#5]
Could you add some arguments to the initial Datastream allowing use behind a proxy. You could then add the argument "proxy={'http':'proxyLocaion:portNumber'}" to your suds.client call when the Datastream object is instantiated.

**Comment by vfilimonov** [comment]
Hello,

thanks for the suggestion!

Could you please try it on your side and submit a PR? I don't have a proxy set to try, and [things might be more complicated than an extra parameter](https://stackoverflow.com/questions/12414600/suds-ignoring-proxy-setting) - so a proper testing is needed.

Best
Vladimir

**Comment by vfilimonov** [comment]
I've added a `proxy` parameter (313fc7b) via `client.set_options` - hopefully it works. It's in the `develop` branch - please test it before I merge it to `master`.

**Comment by alastairbs** [comment]
That change fails with a URL not found error from the initial "suds.client.Client" call.  I proposed a change to your update in the develop branch which keeps your validation and adds the proxy details to the initial "suds.client.Client" call. I have tested the updated code and it works fine through a proxy.

**Comment by vfilimonov** [comment]
OK, I pulled it. So eventually we don't need extra `client.set_options`...

**Comment by vfilimonov** [comment]
Done. Now the updated version is in master and uploaded to pypi. I'm closing the issue for now. 

@alastairbs, thank you very much for the help!
