### ISSUE TITLE
ImportError: cannot import name 'Datastream'

### ISSUE THREAD

**Issue by dhodod** [vfilimonov/pydatastream#6]
Hi,
I'm trying to set up pydatastream under anaconda. I have successfully upgraded pandas and installed suds-py3 and pydatasteam-0.4.0 using pip. When I enter "from pydatastream import Datastream" on the python command line or in a jupyter notebook I get the error in the subject line. Is this a bug or am I missing a step in the setup?

**Comment by vfilimonov** [comment]
Hello,

this is indeed very strange. Could you please show the full traceback? And also: does `import pydatastream` fail with the same error?

BTW, are you using Python 3.x?

Best
Vladimir

**Comment by dhodod** [comment]
Hi, 
Thanks for getting back to me. Yes, I'm using Python 3.5. 

The full traceback is here:
>>> from pydatastream import Datastream
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'Datastream'

The simple import doesn't throw an error message:
import pydatastream
>>> 

The pip install appears to show that all the dependencies are in place:

iMac:~ dhodod$ pip install -e ./Downloads/pydatastream-master --upgrade
Obtaining file:///Users/davidhood/Downloads/pydatastream-master
Requirement already up-to-date: suds-py3 in ./anaconda/lib/python3.5/site-packages (from PyDatastream==0.4.0)
Requirement already up-to-date: pandas in ./anaconda/lib/python3.5/site-packages (from PyDatastream==0.4.0)
Requirement already up-to-date: python-dateutil>=2 in ./anaconda/lib/python3.5/site-packages (from pandas->PyDatastream==0.4.0)
Requirement already up-to-date: pytz>=2011k in ./anaconda/lib/python3.5/site-packages (from pandas->PyDatastream==0.4.0)
Requirement already up-to-date: numpy>=1.7.0 in ./anaconda/lib/python3.5/site-packages (from pandas->PyDatastream==0.4.0)
Requirement already up-to-date: six>=1.5 in ./anaconda/lib/python3.5/site-packages (from python-dateutil>=2->pandas->PyDatastream==0.4.0)
Installing collected packages: PyDatastream
  Running setup.py develop for PyDatastream
Successfully installed PyDatastream-0.4.0

I'm trying it here on a mac but I had a similar problem on a Windows machine. 

Best regards,
David

**Comment by vfilimonov** [comment]
Thanks, David.

Honestly I'm a bit confused. Could it be [some python-3 specific issue](http://python-notes.curiousefficiency.org/en/latest/python_concepts/import_traps.html) (e.g. caused by the line `from pydatastream import *` inside `__init__.py`)? I've never worked with python 3.x so I could only guess at the moment...

And what if you do:
```
import pydatastream as pds
DWE = pds.Datastream(username="DS:XXXX000", password="XXX000")
```
instead of `from pydatastream import Datastream`? If it does not work - could you please tell me what do you see if you do `import pydatastream as pds` and then type `pds.` and hit "Tab"?

**Comment by dhodod** [comment]
Hi Vladimir,

Sorry for the delay in replying.

I found the solution thanks to your last post. I used the 2to3 conversion utility and now it all works beautifully. 
2to3 ./Downloads/pydatastream-master -w

Thanks for your help - it's much appreciated.

Best regards,
David

**Comment by vfilimonov** [comment]
Hello David,

I used `2to3` and pushed changes [here](https://github.com/vfilimonov/pydatastream/commit/65fac7fe26a950774f5fbb0a87bb395270d07bda). Now changes are on the pypi as well and should be retrieved with `pip`/`pip3`.

Could I ask you to do a clean install via 
```
pip install pydatastream
```
(or `pip3` if you use it)? I would appreciate if you could check/confirm that now installation works fine.

Thanks
Vladimir

**Comment by dhodod** [comment]
Hi Vladimir,
I won't have a chance to verify this for a few days but I will get back to you when I can. 
Thanks,
David

**Comment by vfilimonov** [comment]
Sure, no rush - whenever you have time!

**Comment by ceaza** [comment]
Works on WinPython 3.5.1.2

**Comment by dhodod** [comment]
Hi Vladimir,
The new version 0.4.1 worked perfectly for me too. Thanks for updating it. 
Best regards,
David
