### ISSUE TITLE
Static request

### ISSUE THREAD

**Issue by maximedb** [vfilimonov/pydatastream#7]
Hello,

First of all, thank you for this package.

I have a problem when trying to do a static request. For example, running this request 
`DWE.fetch(['D:BAS','D:BASX','HN:BAS','I:BAF','BFA','@BFFAF','S:BAS'], ['ISIN', 'ISINID', 'NAME'], static=True)` 
raises the following error: 
`TypeError: fetch() got an unexpected keyword argument 'static'`

I tried upgrading with `pip install pydatastream --upgrade` but it does not change the outcome.

Do you have an idea what is causing the error ?

Thank you.

**Comment by maximedb** [comment]
Making a copy and importing it as Datastream resolved the issue 👍  It must be related to the upgrade that did not work obviously :-)

**Comment by vfilimonov** [comment]
Perhaps then a "clean" install with `pip uninstall pydatastream` and `pip install pydatastream` should help?

But anyway, I confirm that your request works well for me.
