### ISSUE TITLE
string encoding error

### ISSUE THREAD

**Issue by alastairbs** [vfilimonov/pydatastream#8]
When importing a data item which has a currency symbol in the title I get the following error:

"UnicodeEncodeError: 'ascii' codec can't encode character u'\xa3' in position 0: ordinal not in range(128)"

This was when importing symbol "USDOLLR" with field "ER" (i.e.:  DWE.fetch('USDOLLR','ER', date_from='2015').  The title of the data series has both the £ and $ characters in it.

**Comment by vfilimonov** [comment]
Please check `develop` - it should be fine now

**Comment by alastairbs** [comment]
Yes that fixed it. Thanks.

**Comment by vfilimonov** [comment]
done - now in pypi: v0.4.3
