### ISSUE TITLE
Get an error when proxy is enabled

### ISSUE THREAD

**Issue by abbanerjeersm** [vfilimonov/pydatastream#9]
File "C:\Users\abanerj1\AppData\Roaming\Python\Python35\site-packages\pydatastream\pydatastream.py", line 477, in fetch
    query = self.construct_request(tickers, fields, date, date_from, date_to, freq)
  File "C:\Users\abanerj1\AppData\Roaming\Python\Python35\site-packages\pydatastream\pydatastream.py", line 425, in construct_request
    if isinstance(fields, basestring):
NameError: name 'basestring' is not defined

**Comment by ceaza** [comment]
'basestring' is no longer a type in Python 3. If you change the type to str that should sort issue out. See [http://www.rfk.id.au/blog/entry/preparing-pyenchant-for-python-3/]

**Comment by vfilimonov** [comment]
Thanks, @ceaza !

**Comment by vfilimonov** [comment]
I've pushed a quick suggested fix to the `develop` branch. @ceaza , @abbanerjeersm - could you please check if it works? (perhaps at some point I'll install Python 3 for myself ;-))
If there're no issues - I'll push it to master and pypi.

**Comment by ceaza** [comment]
Thanks @vfilimonov all calls work on winPython 3.5.2.1. Yes, seems that the Python 3 momentum is growing.

**Comment by vfilimonov** [comment]
Done!
